# These are supported funding model platforms

github: rouffi
patreon: rouffi
open_collective: coglab
ko_fi: rouffi
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
